### ISSUE TITLE
Add RuboCop (linter) workflow

### ISSUE THREAD

**Issue by mkienow-r7** [rapid7/recog-ruby#14]
**Is your feature request related to a problem? Please describe.**
Make it easier for contributors and maintainers to ensure code adheres to a proper style and format.

**Describe the solution you'd like**
Run RuboCop on push to main branch and on pull requests.
* Add `.rubocop.yml` configuration to the root directory for controlling RuboCop’s behaviour
* Add workflow `.github/workflows/rubocop.yml` that runs RuboCop on `push` and `pull_request`

**Describe alternatives you've considered**
None

**Additional context**
See equivalent issue in rapid7/recog#417

**Comment by adfoster-r7** [comment]
Closed by https://github.com/rapid7/recog-ruby/pull/15
